python ./main.py \
    --name NO_MU_IN_COMPLEXITY \
    --batch-size 128 \
    --test-batch-size 1000 \
    --epochs 500 \
    --lr 0.001 \
    --weight-mu-mean-init 0.0 \
    --weight-mu-scale-init 0.001 \
    --weight-rho-mean-init -7.0 \
    --weight-rho-scale-init 0.001 \
    --bias-mu-mean-init 0.0 \
    --bias-mu-scale-init 0.001 \
    --bias-rho-mean-init -7.0 \
    --bias-rho-scale-init 0.001 \
    --weight-prior 0.1 \
    --bias-prior 1 \
    --samples 15 \
    --pre-normalization \
